services:
  - type: web
    name: arcaneeth-api
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main_v3:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9